export const environment = {
  production: true,
  pubgApiKey: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxZDhhOTIzMC00ZmQzLTAxM2ItMTc3Ny0xN2UwYjU2OTI4YTIiLCJpc3MiOiJnYW1lbG9ja2VyIiwiaWF0IjoxNjY5NDc5MTc3LCJwdWIiOiJibHVlaG9sZSIsInRpdGxlIjoicHViZyIsImFwcCI6InB1Ymdsb29rdXAifQ.4Kwi7BwfCh2BqAoKebnzHAhTXldwkhZ19VbJbejrlpI'
};
